### ISSUE TITLE
"./_proto/example" "./_proto/example.client" missing

### ISSUE THREAD

**Issue by polkila** [Mitch528/react-native-grpc#9]
Could you please provide 2 files referenced in here. Thanks a lot. I am new to this module and trying to get it worked.
https://github.com/Mitch528/react-native-grpc/blob/fd5660a4c69dca70b64887ac04545cb794b37bfb/example/src/App.tsx#LL6C1-L7C58

**Comment by lesleysin** [comment]
@polkila  These files are generated by a special utility based on the .proto file in the example/protos directory.
To get the same files for your services, run the [protogen.sh](https://github.com/Mitch528/react-native-grpc/blob/main/example/protogen.sh) script

**Comment by polkila** [comment]
> @polkila These files are generated by a special utility based on the .proto file in the example/protos directory. To get the same files for your services, run the [protogen.sh](https://github.com/Mitch528/react-native-grpc/blob/main/example/protogen.sh) script

I got it. Unfortunately **protoc** didn't generated example request with ***.proto** files for service i planned to use.

**Comment by polkila** [comment]
> @polkila These files are generated by a special utility based on the .proto file in the example/protos directory. To get the same files for your services, run the [protogen.sh](https://github.com/Mitch528/react-native-grpc/blob/main/example/protogen.sh) script

@lesleysin Can you give me your './_proto/example' and './_proto/example.client' please?
